In [5]:
import numpy as np
import pandas as pd

In [7]:
!gunzip data/weather_19580901_20180809.csv.gz

In [8]:
df_weather = pd.read_csv('data/weather_19580901_20180809.csv', parse_dates=True, index_col='DATE', sep=',', low_memory=False)

In [9]:
df_weather.head()

,STATION,STATION_NAME,ELEVATION,LATITUDE,LONGITUDE,REPORTTPYE,HOURLYSKYCONDITIONS,HOURLYVISIBILITY,HOURLYPRSENTWEATHERTYPE,HOURLYDRYBULBTEMPF,...,MonthlyMaxSeaLevelPressureTime,MonthlyMinSeaLevelPressureValue,MonthlyMinSeaLevelPressureDate,MonthlyMinSeaLevelPressureTime,MonthlyTotalHeatingDegreeDays,MonthlyTotalCoolingDegreeDays,MonthlyDeptFromNormalHeatingDD,MonthlyDeptFromNormalCoolingDD,MonthlyTotalSeasonToDateHeatingDD,MonthlyTotalSeasonToDateCoolingDD
DATE,,,,,,,,,,,,,,,,,,,,,
1958-09-01 01:00:00,WBAN:23152,BURBANK GLENDALE PASADENA AIRPORT CA US,225.9,34.20056,-118.3575,SAO,NaN,NaN,||FU:04,65,...,-9999,NaN,-9999,-9999,NaN,NaN,NaN,NaN,NaN,NaN
1958-09-01 02:00:00,WBAN:23152,BURBANK GLENDALE PASADENA AIRPORT CA US,225.9,34.20056,-118.3575,SAO,NaN,NaN,||FU:04,64,...,-9999,NaN,-9999,-9999,NaN,NaN,NaN,NaN,NaN,NaN
1958-09-01 03:00:00,WBAN:23152,BURBANK GLENDALE PASADENA AIRPORT CA US,225.9,34.20056,-118.3575,SAO,NaN,NaN,||FU:04,64,...,-9999,NaN,-9999,-9999,NaN,NaN,NaN,NaN,NaN,NaN
1958-09-01 04:00:00,WBAN:23152,BURBANK GLENDALE PASADENA AIRPORT CA US,225.9,34.20056,-118.3575,SAO,NaN,NaN,||FU:04,65,...,-9999,NaN,-9999,-9999,NaN,NaN,NaN,NaN,NaN,NaN
1958-09-01 05:00:00,WBAN:23152,BURBANK GLENDALE PASADENA AIRPORT CA US,225.9,34.20056,-118.3575,SAO,NaN,NaN,||FU:04,63,...,-9999,NaN,-9999,-9999,NaN,NaN,NaN,NaN,NaN,NaN

In [10]:
df_weather[['HOURLYDRYBULBTEMPF']].describe()

       HOURLYDRYBULBTEMPF
count              439891
unique                156
top                    63
freq                17948